app:
  port: 3000

db:
  user: root
  password: P@ssW0rd32!
  host: localhost
  name: pos_system

keycloak:
  url: http://localhost:9090
  clientId: pos-login
  clientSecret: b6izmGJaBOYYichZdOVjWeaQS1lLALVg
  realm: pos-app
  tokenEndpoint: realms/pos-app/protocol/openid-connect/token
