app:
  port: 3000

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  name: oauth_db

oauth:
  client_id: your-client-id
  client_secret: your-client-secret
  auth_url: https://provider.com/oauth2/auth
  token_url: https://provider.com/oauth2/token
  redirect_url: http://localhost:3000/oauth/callback